language: java
jdk:
  - openjdk8

branches:
  only:
  - master

before_install:
  - chmod +x gradlew

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./gradlew uploadArchives; fi'

notifications:
  email: false